# Generated by Django 3.2.4 on 2021-12-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('enterpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('enterpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
