# Generated by Django 3.2.4 on 2021-12-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_auto_20211220_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='deptt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
