# Generated by Django 3.2.4 on 2021-12-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_deptt'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemexpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('etype', models.CharField(max_length=100)),
                ('iname', models.CharField(max_length=100)),
                ('quant', models.CharField(max_length=100)),
                ('amt', models.CharField(max_length=100)),
                ('pacc', models.CharField(max_length=100)),
            ],
        ),
    ]
