# Generated by Django 3.2.4 on 2021-12-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_itemexpen'),
    ]

    operations = [
        migrations.CreateModel(
            name='hrexpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('etype', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('purp', models.CharField(max_length=100)),
                ('amt', models.CharField(max_length=100)),
                ('pacc', models.CharField(max_length=100)),
            ],
        ),
    ]
