# Generated by Django 3.2.4 on 2021-12-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_hrexpen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemexpen',
            name='tid',
        ),
    ]
