# Generated by Django 3.2.4 on 2021-12-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_auto_20211221_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerr',
            new_name='reg1',
        ),
        migrations.DeleteModel(
            name='loginn',
        ),
    ]
