# Generated by Django 3.2.4 on 2021-12-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='num',
            new_name='numm',
        ),
    ]
