# Generated by Django 3.2.4 on 2021-12-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_rename_num_create_numm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hrexpen',
            new_name='ex8',
        ),
    ]
