# Generated by Django 3.2.4 on 2021-12-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_rename_sname_ex8_stname'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('et', models.CharField(max_length=100)),
                ('an', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('it', models.CharField(max_length=100)),
                ('fd', models.CharField(max_length=100)),
                ('td', models.CharField(max_length=100)),
            ],
        ),
    ]
